# https://taskfile.dev

version: '3'

vars:
  GREETING: gungnir compiler!

tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
    silent: true
  
  build:
    cmds:
      - go build ./main.go ./repl.go
