# https://taskfile.dev

version: '3'

vars:
  GREETING: gungnir compiler!

tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
    silent: true
  
  run:
    cmds:
      - go run ./main.go ./parser.go ./data.go

  build:
    cmds:
      - go build ./main.go ./parser.go ./data.go
